alias hs="history | grep"
alias desktop="cd ~/Desktop"
alias downloads="cd ~/Downloads"
alias documents="cd ~/Documents"

alias gac="git add . && git commit -a -m "
alias myip="curl http://ipecho.net/plain; echo"
alias update="sudo apt-get update && sudo apt-get upgrade"
alias editrc="nano ~/.bashrc"
alias edital="nano ~/.bash_aliases"
alias editp="nano ~/.profile"
alias killall="pkill -f"
alias path="$PATH"
alias bestkey="ssh-keygen -t ed25519 -a 100"
alias showconfig="cat ~/.ssh/config | less"

